feat: multiarch release for 0.9.3 (#16)
* ci: sync workflows from fix-multiarch

* ci: sync ghcr workflows

diff --git a/.github/workflows/cicd-pull-request.yml b/.github/workflows/cicd-pull-request.yml
--- a/.github/workflows/cicd-pull-request.yml
+++ b/.github/workflows/cicd-pull-request.yml
@@ -1,26 +1,22 @@
-name: Pull Request
+name: CICD-PULL-REQUEST
 
 on:
-  pull_request:
-    types: [ labeled ]
-    branches:
-      - main
-      - release-*
+  pull_request_review:
+    types: [submitted]
 
 env:
   GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-  BASE_BRANCH: origin/main
+  BASE_BRANCH: origin/${{ github.event.pull_request.base.ref }}
   GO_VERSION: "1.21"
 
 jobs:
   trigger-mode:
     name: trigger mode
-    if: github.event.action == 'labeled' && (github.event.label.name == 'approved' || github.event.label.name == 'pre-approve')
+    if: github.event.review.state == 'approved'
     runs-on: ubuntu-latest
     outputs:
       trigger-mode: ${{ steps.get_trigger_mode.outputs.trigger_mode }}
-      git-commit: ${{ steps.get_git_info.outputs.git_commit }}
-      git-version: ${{ steps.get_git_info.outputs.git_version }}
+      matrix: ${{ steps.get_trigger_mode.outputs.matrix }}
     steps:
       - name: Cancel Previous Runs
         uses: styfle/cancel-workflow-action@0.11.0
@@ -35,39 +31,37 @@ jobs:
 
       - name: Get trigger mode
         id: get_trigger_mode
-        env:
-          HEAD_REF: ${{ github.event.pull_request.head.ref }}
         run: |
-          if [[ "${HEAD_REF}" != "main" ]]; then
-              git checkout -b ${HEAD_REF} --track origin/${HEAD_REF}
+          if [[ "${{ github.event.pull_request.head.ref }}" != "main" ]]; then
+              git checkout -b ${{ github.event.pull_request.head.ref }} --track origin/${{ github.event.pull_request.head.ref }}
           fi
           TRIGGER_MODE=`bash .github/utils/utils.sh --type 6 \
-              --branch-name "${HEAD_REF}" \
+              --branch-name "${{ github.event.pull_request.head.ref }}" \
               --base-branch "${{ env.BASE_BRANCH }}"`
           echo $TRIGGER_MODE
           echo trigger_mode=$TRIGGER_MODE >> $GITHUB_OUTPUT
 
-      - name: get git info
-        id: get_git_info
-        run: |
-          GIT_COMMIT=$(git rev-list -1 HEAD)
-          GIT_VERSION=$(git describe --always --abbrev=0 --tag)
-          echo git_commit=$GIT_COMMIT >> $GITHUB_OUTPUT
-          echo git_version=$GIT_VERSION >> $GITHUB_OUTPUT
+          TEST_PACKAGES=`bash .github/utils/utils.sh --type 16 \
+              --trigger-type "$TRIGGER_MODE" \
+              --test-pkgs "${{ vars.TEST_PKGS }}" \
+              --test-check "${{ vars.TEST_CHECK }}" \
+              --test-pkgs-first "${{ vars.TEST_PKGS_FIRST }}" \
+              --ignore-pkgs "${{ vars.SKIP_CHECK_PKG }}"`
+          echo "$TEST_PACKAGES"
+          echo "matrix={\"include\":[$TEST_PACKAGES]}" >> $GITHUB_OUTPUT
 
-  pr-pre-check:
+  test-parallel:
+    name: test
     needs: trigger-mode
-    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') }}
+    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name == github.repository }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
-      matrix:
-        ops: [ 'manifests', 'mod-vendor', 'generate', 'lint', 'staticcheck', 'test' ]
+      matrix: ${{ fromJSON(needs.trigger-mode.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v4
       - name: install lib
         run: |
-          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
           sudo apt-get update
           sudo apt-get install -y --no-install-recommends \
             libbtrfs-dev \
@@ -81,27 +75,47 @@ jobs:
       - name: Install golangci-lint
         if: matrix.ops == 'lint'
         run: |
-          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
+          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
 
       - name: make ${{ matrix.ops }}
+        if: ${{ ! contains(matrix.ops, '/') }}
         run: |
           make ${{ matrix.ops }}
-          FILE_CHANGES=`git diff --name-only ${{ github.sha }}`
-          if [[ ("${{ matrix.ops }}" == 'generate' || "${{ matrix.ops }}" == 'manifests') && -n "$FILE_CHANGES" ]]; then
-              echo $FILE_CHANGES
-              echo "make "${{ matrix.ops }}" causes inconsistent files"
-              exit 1
+
+      - name: make test ${{ matrix.ops }}
+        if: ${{ contains(matrix.ops, '/') }}
+        run: |
+          if [[ -d "./${{ matrix.ops }}" ]]; then
+              make test TEST_PACKAGES=./${{ matrix.ops }}/...
           fi
 
+  make-test:
+    needs: trigger-mode
+    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name != github.repository }}
+    outputs:
+      runner-name: ${{ steps.get_runner_name.outputs.runner_name }}
+    runs-on: [ self-hosted, gke-runner-go1.21 ]
+    steps:
+      - uses: actions/checkout@v4
+      - name: make mod-vendor
+        run: |
+          make mod-vendor
+
+      - name: make lint
+        run: |
+          make lint
+
+      - name: make test
+        run: |
+          make test
+
       - name: ignore cover pkgs
-        if: matrix.ops == 'test'
         run: |
           bash .github/utils/utils.sh --type 14 \
               --file cover.out \
               --ignore-pkgs "${{ vars.IGNORE_COVERAGE_PKG }}"
 
       - name: upload coverage report
-        if: matrix.ops == 'test'
         uses: codecov/codecov-action@v3
         continue-on-error: true
         with:
@@ -111,23 +125,44 @@ jobs:
           name: codecov-report
           verbose: true
 
+      - name: kill kube-apiserver and etcd
+        id: get_runner_name
+        if: ${{ always() }}
+        run: |
+          echo runner_name=${RUNNER_NAME} >> $GITHUB_OUTPUT
+          bash .github/utils/utils.sh --type 8
+
+  remove-runner:
+    needs: [ trigger-mode, make-test ]
+    runs-on: ubuntu-latest
+    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name != github.repository && always()  }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: remove runner
+        run: |
+          bash .github/utils/utils.sh --type 9 \
+              --github-token ${{ env.GITHUB_TOKEN }} \
+              --runner-name ${{ needs.make-test.outputs.runner-name }}
+
   check-image:
+    permissions:
+      contents: read
+      id-token: write
     needs: trigger-mode
     if: contains(needs.trigger-mode.outputs.trigger-mode, '[docker]')
-    uses: apecloud/apecloud-cd/.github/workflows/release-image-check.yml@v0.1.64
+    uses: apecloud/apecloud-cd/.github/workflows/release-image-check.yml@v0.1.24
     with:
       MAKE_OPS_PRE: "generate"
       IMG: "apecloud/kubeblocks"
       GO_VERSION: "1.21"
       BUILDX_PLATFORMS: "linux/amd64"
       DOCKERFILE_PATH: "./docker/Dockerfile"
-      BUILDX_ARGS: |
-        VERSION=${{ needs.trigger-mode.outputs.git-version }}
-        GIT_COMMIT=${{ needs.trigger-mode.outputs.git-commit }}
-        GIT_VERSION=${{ needs.trigger-mode.outputs.git-version }}
     secrets: inherit
 
   check-tools-image:
+    permissions:
+      contents: read
+      id-token: write
     needs: trigger-mode
     if: contains(needs.trigger-mode.outputs.trigger-mode, '[docker]')
     uses: apecloud/apecloud-cd/.github/workflows/release-image-check.yml@v0.1.24
@@ -140,6 +175,9 @@ jobs:
     secrets: inherit
 
   check-datascript-image:
+    permissions:
+      contents: read
+      id-token: write
     needs: trigger-mode
     if: contains(needs.trigger-mode.outputs.trigger-mode, '[docker]')
     uses: apecloud/apecloud-cd/.github/workflows/release-image-check.yml@v0.1.24
@@ -150,6 +188,9 @@ jobs:
     secrets: inherit
 
   check-dataprotection-image:
+    permissions:
+      contents: read
+      id-token: write
     needs: trigger-mode
     if: contains(needs.trigger-mode.outputs.trigger-mode, '[docker]')
     uses: apecloud/apecloud-cd/.github/workflows/release-image-check.yml@v0.1.24
@@ -176,13 +217,22 @@ jobs:
 
   pr-check:
     name: make test
-    needs: [ trigger-mode, pr-pre-check, check-image, check-tools-image, check-datascript-image, check-dataprotection-image, check-helm ]
-    if: ${{ github.event.action == 'labeled' && (github.event.label.name == 'approved' || github.event.label.name == 'pre-approve') && always() }}
+    needs: [ trigger-mode, test-parallel, make-test, check-image, check-tools-image, check-datascript-image, check-dataprotection-image, check-helm ]
+    if: ${{ github.event.review.state == 'approved' && always() }}
     runs-on: ubuntu-latest
     steps:
-      - name: pr pre check
+      - name: test parallel check
+        if: github.event.pull_request.head.repo.full_name == github.repository
         run: |
-          if [[ "${{ needs.pr-pre-check.result }}" == "failure" || "${{ needs.pr-pre-check.result }}" == "cancelled" ]]; then
+          if [[ "${{ needs.test-parallel.result }}" == "failure" || "${{ needs.test-parallel.result }}" == "cancelled" ]]; then
+              echo "test parallel fail"
+              exit 1
+          fi
+
+      - name: make test check
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          if [[ "${{ needs.make-test.result }}" == "failure" || "${{ needs.make-test.result }}" == "cancelled" ]]; then
               echo "make test fail"
               exit 1
           fi
diff --git a/.github/workflows/release-helm-chart.yml b/.github/workflows/release-helm-chart.yml
--- a/.github/workflows/release-helm-chart.yml
+++ b/.github/workflows/release-helm-chart.yml
@@ -1,4 +1,4 @@
-name: Release Charts
+name: Release Chart
 
 on:
   workflow_dispatch:
@@ -14,7 +14,6 @@ on:
 env:
   GH_TOKEN: ${{ github.token }}
   RELEASE_VERSION: ${{ github.ref_name }}
-  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
 jobs:
   release-version:
@@ -34,49 +33,60 @@ jobs:
           RELEASE_VERSION_BUMP="${RELEASE_VERSION/v/}"
           echo release_version_bump=$RELEASE_VERSION_BUMP >> $GITHUB_OUTPUT
 
+  precheck-secrets:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Docker Hub secrets
+        run: |
+          missing=()
+          if [[ -z "${{ secrets.DOCKER_REGISTRY_USER }}" ]]; then
+            missing+=("DOCKER_REGISTRY_USER")
+          fi
+          if [[ -z "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" ]]; then
+            missing+=("DOCKER_REGISTRY_PASSWORD")
+          fi
+          if (( ${#missing[@]} > 0 )); then
+            echo "::error title=Missing secrets::${missing[*]} are not set in repository secrets"
+            exit 1
+          fi
+
   release-chart:
     needs: [ release-version ]
-    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.86
+    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.43
     with:
       MAKE_OPS: "bump-chart-ver"
       VERSION: "${{ needs.release-version.outputs.release-version }}"
       CHART_NAME: "kubeblocks"
       CHART_DIR: "deploy/helm"
-      APECD_REF: "v0.1.86"
+      APECD_REF: "v0.1.43"
       MAKE_OPS_POST: "install"
       GO_VERSION: "1.21"
     secrets: inherit
 
   release-addons-chart:
     needs: [ release-chart ]
-    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.86
+    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.52
     with:
       GITHUB_REPO: "apecloud/kubeblocks-addons"
-      GITHUB_REF: "${{ github.ref_name }}"
+      GITHUB_REF: ${{ github.ref }}
       CHART_DIR: "addons"
-      APECD_REF: "v0.1.86"
+      APECD_REF: "v0.1.52"
       ENABLE_JIHU: false
     secrets: inherit
 
-  release-addons-cluster-chart:
-    needs: [ release-addons-chart ]
-    uses: apecloud/apecloud-cd/.github/workflows/trigger-workflow.yml@v0.1.86
-    with:
-      GITHUB_REPO: "apecloud/kubeblocks-addons"
-      BRANCH_NAME: "${{ github.ref_name }}"
-      WORKFLOW_ID: "release-addons-cluster-chart.yml"
-      APECD_REF: "v0.1.86"
-    secrets: inherit
-
   release-charts-image:
-    needs: [ release-version, release-addons-chart ]
-    uses: apecloud/apecloud-cd/.github/workflows/release-image-cache.yml@v0.1.86
+    permissions:
+      contents: read
+      id-token: write
+    needs: [ release-version, release-addons-chart, precheck-secrets ]
+    uses: ./.github/workflows/release-image-cache.yml
     with:
       MAKE_OPS_PRE: "helm-package VERSION=${{ needs.release-version.outputs.release-version-bump }}"
-      IMG: "apecloud/kubeblocks-charts"
+      IMG: "wallykk/kubeblocks-charts"
       VERSION: "${{ needs.release-version.outputs.release-version }}"
+      BUILDX_PLATFORMS: "linux/amd64,linux/arm64"
       GO_VERSION: "1.21"
-      APECD_REF: "v0.1.86"
+      APECD_REF: "v0.1.24"
       DOCKERFILE_PATH: "./docker/Dockerfile-charts"
     secrets: inherit
 
@@ -120,13 +130,16 @@ jobs:
           key: ${{ steps.release_message.outputs.artifact_key }}
 
   send-message:
+    permissions:
+      contents: read
+      id-token: write
     needs: [ release-message ]
     if: ${{ always() && github.event.action == 'published' }}
-    uses: apecloud/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.86
+    uses: apecloud/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.38
     with:
       TYPE: "2"
       CONTENT: "release chart ${{ needs.release-message.outputs.release-version }} ${{ needs.release-message.outputs.content-result }}"
-      APECD_REF: "v0.1.86"
+      APECD_REF: "v0.1.38"
     secrets: inherit
 
   get-addons-chart-dir:
@@ -139,7 +152,7 @@ jobs:
         with:
           repository: apecloud/kubeblocks-addons
           path: kubeblocks-addons
-          ref: "${{ github.ref_name }}"
+          ref: ${{ github.ref }}
       - name: get addons chart dir
         id: get_addons_chart_dir
         run: |
@@ -160,64 +173,11 @@ jobs:
     strategy:
       fail-fast: false
       matrix: ${{ fromJSON(needs.get-addons-chart-dir.outputs.matrix) }}
-    uses: apecloud/apecloud-cd/.github/workflows/release-charts-jihu.yml@v0.1.86
+    uses: apecloud/apecloud-cd/.github/workflows/release-charts-jihu.yml@v0.1.52
     with:
       GITHUB_REPO: "apecloud/kubeblocks-addons"
-      GITHUB_REF: "${{ github.ref_name }}"
+      GITHUB_REF: ${{ github.ref }}
       CHART_DIR: "addons"
       SPECIFY_CHART: "${{ matrix.addon-name }}"
-      APECD_REF: "v0.1.86"
-    secrets: inherit
-
-  release-addons-chart-ent:
-    needs: [ release-chart ]
-    uses: apecloud/apecloud-cd/.github/workflows/release-charts-enterprise.yml@v0.1.86
-    with:
-      GITHUB_REPO: "apecloud/apecloud-addons"
-      GITHUB_REF: "${{ github.ref_name }}"
-      CHART_DIR: "addons"
-      APECD_REF: "v0.1.86"
-      ENABLE_JIHU: false
-    secrets: inherit
-
-  get-addons-chart-dir-ent:
-    runs-on: ubuntu-latest
-    outputs:
-      matrix: ${{ steps.get_addons_chart_dir.outputs.matrix }}
-    steps:
-      - name: Checkout apecloud-addons Code
-        uses: actions/checkout@v4
-        with:
-          repository: apecloud/apecloud-addons
-          path: apecloud-addons
-          ref: "${{ github.ref_name }}"
-          token: ${{ env.GITHUB_TOKEN }}
-
-      - name: get addons chart dir
-        id: get_addons_chart_dir
-        run: |
-          addons_list=$(ls apecloud-addons/addons)
-          ADDONS_DIR=""
-          for addons_name in $( echo "$addons_list" ); do
-              if [[ -z "$ADDONS_DIR" ]]; then
-                  ADDONS_DIR="{\"addon-name\":\"$addons_name\"}"
-              else
-                  ADDONS_DIR="$ADDONS_DIR,{\"addon-name\":\"$addons_name\"}"
-              fi
-          done
-          echo "$ADDONS_DIR"
-          echo "matrix={\"include\":[$ADDONS_DIR]}" >> $GITHUB_OUTPUT
-
-  release-addons-chart-jihu-ent:
-    needs: [ get-addons-chart-dir-ent ]
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJSON(needs.get-addons-chart-dir-ent.outputs.matrix) }}
-    uses: apecloud/apecloud-cd/.github/workflows/release-charts-jihu-enterprise.yml@v0.1.86
-    with:
-      GITHUB_REPO: "apecloud/apecloud-addons"
-      GITHUB_REF: "${{ github.ref_name }}"
-      CHART_DIR: "addons"
-      SPECIFY_CHART: "${{ matrix.addon-name }}"
-      APECD_REF: "v0.1.86"
+      APECD_REF: "v0.1.52"
     secrets: inherit
