ci: publish images to ghcr.io/labring (#11)

diff --git a/.github/workflows/release-helm-chart.yml b/.github/workflows/release-helm-chart.yml
--- a/.github/workflows/release-helm-chart.yml
+++ b/.github/workflows/release-helm-chart.yml
@@ -33,6 +33,23 @@ jobs:
           RELEASE_VERSION_BUMP="${RELEASE_VERSION/v/}"
           echo release_version_bump=$RELEASE_VERSION_BUMP >> $GITHUB_OUTPUT
 
+  precheck-secrets:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Docker Hub secrets
+        run: |
+          missing=()
+          if [[ -z "${{ secrets.DOCKER_REGISTRY_USER }}" ]]; then
+            missing+=("DOCKER_REGISTRY_USER")
+          fi
+          if [[ -z "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" ]]; then
+            missing+=("DOCKER_REGISTRY_PASSWORD")
+          fi
+          if (( ${#missing[@]} > 0 )); then
+            echo "::error title=Missing secrets::${missing[*]} are not set in repository secrets"
+            exit 1
+          fi
+
   release-chart:
     needs: [ release-version ]
     uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.43
@@ -58,12 +75,16 @@ jobs:
     secrets: inherit
 
   release-charts-image:
-    needs: [ release-version, release-addons-chart ]
-    uses: apecloud/apecloud-cd/.github/workflows/release-image-cache.yml@v0.1.24
+    permissions:
+      contents: read
+      id-token: write
+    needs: [ release-version, release-addons-chart, precheck-secrets ]
+    uses: ./.github/workflows/release-image-cache.yml
     with:
       MAKE_OPS_PRE: "helm-package VERSION=${{ needs.release-version.outputs.release-version-bump }}"
-      IMG: "apecloud/kubeblocks-charts"
+      IMG: "wallykk/kubeblocks-charts"
       VERSION: "${{ needs.release-version.outputs.release-version }}"
+      BUILDX_PLATFORMS: "linux/amd64,linux/arm64"
       GO_VERSION: "1.21"
       APECD_REF: "v0.1.24"
       DOCKERFILE_PATH: "./docker/Dockerfile-charts"
@@ -109,6 +130,9 @@ jobs:
           key: ${{ steps.release_message.outputs.artifact_key }}
 
   send-message:
+    permissions:
+      contents: read
+      id-token: write
     needs: [ release-message ]
     if: ${{ always() && github.event.action == 'published' }}
     uses: apecloud/apecloud-cd/.github/workflows/feishui-message.yml@v0.1.38
@@ -157,6 +181,3 @@ jobs:
       SPECIFY_CHART: "${{ matrix.addon-name }}"
       APECD_REF: "v0.1.52"
     secrets: inherit
-
-
-
